"""
Render the paper to IEEEtran LaTeX.

Reads the document model from content.py and writes a two-column IEEE paper
plus the figure includes. The bibliography is the checked-in references.bib;
this script does not generate it.

Journal is the default because that is the submission target. Conference mode
is kept because the earlier draft used it and it is one flag away.

    python docs/paper/render_latex.py                     # journal
    python docs/paper/render_latex.py --mode conference
    python docs/paper/render_latex.py --out /tmp/paper.tex

To build a PDF:

    cd docs/paper && pdflatex orbitguard_ieee && bibtex orbitguard_ieee \\
        && pdflatex orbitguard_ieee && pdflatex orbitguard_ieee

IEEEtran.cls ships alongside this file, so the source compiles without a full
TeX Live publisher-styles install; any TeX distribution or Overleaf will do.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from content import CITE_RE, REF_RE, document                     # noqa: E402

# Characters LaTeX treats as syntax. Backslash must be substituted first, and
# via a placeholder, or the replacements below would corrupt each other.
ESCAPES = [
    ("\\", "\x00"),
    ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
    ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
    ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
    ("\x00", r"\textbackslash{}"),
]

# Typographic substitutions applied after escaping, so they can emit macros.
TYPO = [
    ("—", "---"), ("–", "--"),
    ("±", r"$\pm$"), ("≤", r"$\leq$"), ("≥", r"$\geq$"), ("×", r"$\times$"),
    ("'", "'"), ("'", "'"), ('"', "``"), ('"', "''"),
]


#: A bare URL in the prose. Left to the escaper it would come out as literal
#: text with an escaped underscore and no line-breaking, so it is handled as a
#: marker and wrapped in \url{} instead.
URL_RE = re.compile(r"https?://[^\s,)]+[^\s,).]")

MARKER_RE = re.compile(
    f"(?:{CITE_RE.pattern})|(?:{REF_RE.pattern})|(?:{URL_RE.pattern})")


def esc(text: str) -> str:
    """Escape a run of plain prose for LaTeX."""
    for a, b in ESCAPES:
        text = text.replace(a, b)
    for a, b in TYPO:
        text = text.replace(a, b)
    return text


def tex(text: str) -> str:
    """
    Escape prose, turning [@key, key2] into \\cite{key,key2} and [#label] into
    a numbered cross-reference.

    The text is split on those markers so the keys never reach the escaper — an
    underscore in a bibkey would otherwise become \\_ and the reference would
    silently fail to resolve, which LaTeX reports only as a "??" in the output.
    """
    out, last = [], 0
    for m in MARKER_RE.finditer(text):
        out.append(esc(text[last:m.start()]))
        body = m.group(0)
        if body.startswith("http"):
            out.append(f"\\url{{{body}}}")
        elif body.startswith("[@"):
            keys = ",".join(k.strip() for k in body[2:-1].split(","))
            out.append(f"\\cite{{{keys}}}")
        else:
            label = body[2:-1]
            kind = ("Fig." if label.startswith("fig:")
                    else "Section" if label.startswith("sec:") else "Table")
            out.append(f"{kind}~\\ref{{{label}}}")
        last = m.end()
    out.append(esc(text[last:]))
    return "".join(out)


def preamble(meta: dict, mode: str) -> str:
    """
    IEEEtran preamble for `mode`, which is "journal" or "conference".

    The two differ by more than a class option. A journal paper wants the
    authors on one line under the title rather than in side-by-side blocks, and
    \\IEEEoverridecommandlockouts is a conference-template hack that IEEEtran
    warns about in journal mode — so both are switched here rather than left to
    whoever compiles the file.
    """
    if mode == "journal":
        # \IEEEauthorblockN/A are conference macros; journal mode wants a plain
        # author line, with the affiliation as a thanks footnote.
        names = ", ".join(esc(a) for a in meta["authors"])
        author_block = (f"{names}\n"
                        f"\\thanks{{All authors are with the "
                        f"{esc(meta['affiliation'])}.}}")
        classopt = "journal"
        lockouts = ""
    else:
        author_block = "\n\\and\n".join(
            f"\\IEEEauthorblockN{{{esc(a)}}}\n"
            f"\\IEEEauthorblockA{{\\textit{{{esc(meta['affiliation'])}}}}}"
            for a in meta["authors"])
        classopt = "conference"
        lockouts = "\\IEEEoverridecommandlockouts\n"

    return f"""\
%% Generated by docs/paper/render_latex.py --mode {mode} — do not edit by hand.
%% Edit the prose in docs/paper/content.py, or re-run the experiment whose
%% artifact produced the number you want to change.
\\documentclass[{classopt}]{{IEEEtran}}
{lockouts}
\\usepackage{{cite}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{graphicx}}
\\usepackage{{booktabs}}
\\usepackage{{multirow}}
\\usepackage{{url}}
\\usepackage[hidelinks]{{hyperref}}
\\usepackage{{listings}}
\\usepackage{{xcolor}}

\\lstset{{
  basicstyle=\\ttfamily\\scriptsize,
  breaklines=true,
  frame=single,
  rulecolor=\\color{{black!30}},
  columns=fullflexible,
  keepspaces=true,
}}

\\graphicspath{{{{figures/}}}}

\\begin{{document}}

\\title{{{esc(meta['title'])}}}

\\author{{
{author_block}
}}

\\maketitle
"""


def render_table(t: dict) -> str:
    """
    A booktabs table, in a table* float when it needs both columns.

    `groups` optionally adds a spanning header row — used by the ablation
    table, where nine of the ten columns are three metrics repeated under three
    conditions and would be unreadable without it.
    """
    ncol = len(t["headers"])
    wide = t.get("wide", False)
    env = "table*" if wide else "table"
    # The wide table carries ten narrow numeric columns; the default column
    # separation overflows the text block, so it is tightened locally.
    colspec = "l" + "r" * (ncol - 1)
    lines = [f"\\begin{{{env}}}[!t]",
             "\\centering",
             f"\\caption{{{tex(t['caption'])}}}",
             f"\\label{{{t['label']}}}"]
    # Tightened for every table, not just the wide ones: a single IEEE column
    # is ~3.5 in, and at the default column separation the four- and
    # five-column tables overflow it and print into the neighbouring column.
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\footnotesize")
    lines.append(f"\\begin{{tabular}}{{{colspec}}}")
    lines.append("\\toprule")

    if t.get("groups"):
        cells, rules, col = [], [], 1
        for name, span in t["groups"]:
            if span == 1 and not name:
                cells.append("")
            else:
                cells.append(f"\\multicolumn{{{span}}}{{c}}{{{esc(name)}}}")
                if name:
                    rules.append(f"\\cmidrule(lr){{{col}-{col+span-1}}}")
            col += span
        lines.append(" & ".join(cells) + r" \\")
        lines.append("".join(rules))

    lines.append(" & ".join(esc(h) for h in t["headers"]) + r" \\")
    lines.append("\\midrule")
    for i, row in enumerate(t["rows"]):
        cells = [esc(str(c)) for c in row]
        if t.get("bold_first_row") and i == 0:
            cells = [f"\\textbf{{{c}}}" for c in cells]
        lines.append(" & ".join(cells) + r" \\")
    lines += ["\\bottomrule", "\\end{tabular}", f"\\end{{{env}}}"]
    return "\n".join(lines)


def render_figure(f: dict) -> str:
    wide = f.get("wide", False)
    env = "figure*" if wide else "figure"
    width = "\\textwidth" if wide else "\\columnwidth"
    return "\n".join([
        f"\\begin{{{env}}}[!t]",
        "\\centering",
        f"\\includegraphics[width={width}]{{{f['stem']}.pdf}}",
        f"\\caption{{{tex(f['caption'])}}}",
        f"\\label{{{f['label']}}}",
        f"\\end{{{env}}}",
    ])


def build(out_path: Path, mode: str = "journal") -> None:
    doc = document()
    meta = next(v for k, v in doc if k == "title")
    parts = [preamble(meta, mode)]

    for kind, payload in doc:
        if kind == "title":
            continue
        elif kind == "abstract":
            parts.append(f"\\begin{{abstract}}\n{tex(payload)}\n\\end{{abstract}}")
        elif kind == "keywords":
            kws = ", ".join(esc(k) for k in payload)
            parts.append(f"\\begin{{IEEEkeywords}}\n{kws}\n\\end{{IEEEkeywords}}")
        elif kind == "h1":
            # A section carries a label only when the prose points at it.
            text = payload["text"] if isinstance(payload, dict) else payload
            parts.append(f"\\section{{{tex(text)}}}")
            if isinstance(payload, dict) and payload.get("label"):
                parts.append(f"\\label{{{payload['label']}}}")
        elif kind == "h2":
            parts.append(f"\\subsection{{{tex(payload)}}}")
        elif kind == "p":
            parts.append(tex(payload))
        elif kind == "bullets":
            items = "\n".join(f"  \\item {tex(b)}" for b in payload)
            parts.append(f"\\begin{{itemize}}\n{items}\n\\end{{itemize}}")
        elif kind == "table":
            parts.append(render_table(payload))
        elif kind == "figure":
            parts.append(render_figure(payload))
        elif kind == "code":
            parts.append(f"\\begin{{lstlisting}}\n{payload}\n\\end{{lstlisting}}")

    parts.append("\\bibliographystyle{IEEEtran}")
    parts.append("\\bibliography{references}")
    parts.append("\\end{document}")

    out_path.write_text("\n\n".join(parts) + "\n")

    n_cite = len({k.strip() for _, v in doc if isinstance(v, str)
                  for m in CITE_RE.finditer(v) for k in m.group(1).split(",")})
    print(f"  Saved -> {out_path}  [{mode}]")
    print(f"  {len(doc)} blocks, {n_cite} distinct citations")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["journal", "conference"],
                    default="journal",
                    help="IEEEtran class. Journal is the submission target; "
                         "conference is kept because the earlier draft used it "
                         "and reviewers may ask to see it.")
    ap.add_argument("--out", default=None,
                    help="default: orbitguard_ieee.tex for journal, "
                         "orbitguard_ieee_conference.tex for conference")
    args = ap.parse_args()
    out = Path(args.out) if args.out else HERE / (
        "orbitguard_ieee.tex" if args.mode == "journal"
        else "orbitguard_ieee_conference.tex")
    build(out, args.mode)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
